## NUMPY

In [1]:
import numpy as np

In [2]:
# check all the functions in numpy using 'dir': When you apply dir on numpy then the list of methods and attirbutes are listed as output

print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [3]:
# we can use all attributes mentioned above , like to find square root of any , use 'sqrt'

np.sqrt(10)

3.1622776601683795

In [4]:
# Min & Max:

print('Minimum',np.amin([25,89,9,7]))

print('Maximum',np.amax([25,89,9,7]))

Minimum 7
Maximum 89


In [5]:
# Round off to next number: 'ceil' is used for rounding off the number.

np.ceil(90.09)

91.0

In [6]:
# multiple operations/functions: we can use multiple attributes in a single line

np.ceil(np.sqrt(10))

4.0

In [7]:
np.ceil(np.sum(np.sqrt([9,16,25])))

12.0

In [8]:
# Array: 

np.array([5,20,28])

array([ 5, 20, 28])

In [9]:
type([ 5, 20, 28])

list

In [10]:
#defining a variable to create array
xyz=np.array([5,20,28])

In [11]:
type(xyz)      # now this is array , as we have defined it in a variable (xyz)

numpy.ndarray

In [12]:
# Two Dimensions:
a=np.array([[1,2],[3,4],[5,6]])
print("type-",a.dtype)     #dtype meand datatype of a

print('\n',a)      # to print a

type- int32

 [[1 2]
 [3 4]
 [5 6]]


In [13]:
# datatype conversion:

np.array([1,2,3],dtype=float)     #converting int to float


array([1., 2., 3.])

In [14]:
# Convert a list into array:

a=[1,2]
c=np.array(a)
type(c)

numpy.ndarray

In [15]:
# Copy array into array:

b=np.asarray(c)
print(b)

[1 2]


## MATRIX


In [16]:
my_mat = [[1,2,3],[4,6,7],[9,7,8]]
mat= np.array(my_mat)
print("type/class of this object",type(mat))
print("here is the matrix\n.......\n",mat,"\n..........")
print("dimension of the matrix:",mat.ndim)
print("size of the matrix:",mat.size)
print("shape of the matrix:",mat.shape)
print("datatype of the matrix:",mat.dtype)

type/class of this object <class 'numpy.ndarray'>
here is the matrix
.......
 [[1 2 3]
 [4 6 7]
 [9 7 8]] 
..........
dimension of the matrix: 2
size of the matrix: 9
shape of the matrix: (3, 3)
datatype of the matrix: int32


## arange and linspace


In [17]:
# 'arange' in NUMPY as similar to 'range' in python . 

# In 'range' we can only use 'int values' , but in 'arange' we can use int as well as float values.

list(range(10,20,3.5))   # here range cannot use float values

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
import numpy as np

In [32]:
a= np.arange(2,10.5,.4)# here arnage accepted float values
a

array([ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,  4.8,  5.2,  5.6,  6. ,
        6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,  9.2,  9.6, 10. , 10.4])

In [33]:
# Reverse order:

a[::-1]

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,
        6. ,  5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ])

In [34]:
print('every 5th number from 50 in reverse order\n',np.arange(50,-1,-5))

every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5  0]


In [ ]:
# LINSPACE : linear space with equal space within each value of range.

print('lineraly spaced number between 10 and 40 \n.................')
print(np.linspace(10,40,5)) 

In [35]:
# Include end point and check space between the points 
# By default end point = true
# By default restep = false

# Signature: np.linspace(start , stop,num=50 endpoint = true , retstep = false)

np.linspace(2.0, 3.0, num=4 ,endpoint= False , retstep = True)  # endpoint false means end point excluded i.e 3 is excluded.
                                                        #retstep True means we want to know the stepsize b/w values.

(array([2.  , 2.25, 2.5 , 2.75]), 0.25)

In [37]:
np.linspace(2.0, 3.0, num=4 )   # by default ene point is True i.e included , 3 and restep is false.


array([2.        , 2.33333333, 2.66666667, 3.        ])

In [36]:
# same with endpoint = True 

np.linspace(2.0, 3.0, num=4, endpoint=True , retstep = False) # here retstep is false means step size is not mntioned.

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [38]:
b = np.linspace(789.98,890.97 , num=5 , retstep = True)
b

(array([789.98  , 815.2275, 840.475 , 865.7225, 890.97  ]), 25.247500000000002)

# MATRIX CREATION :

# MATRIX DIMENSIONS ARE ALWAYSSEPCIFIED BY TUPLES '()'

In [31]:
# TO generate Zeros matrix using 'np.zeros' of any order
# np.zeros(this may be any order)
np.zeros(5)  # order is basically 1*5  i.e one row , 5 columns or VECTOR OF ZEROS.


array([0., 0., 0., 0., 0.])

In [30]:
# MATRIX OF ZEROS:

# np.zeros(row,column)

np.zeros((3,4))# first bracket is for syntax , inner is for (row,column)


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
# VECTORS /MATRIX OF ONES :

# np.ones(n) n may be anything 

np.ones(5)

array([1., 1., 1., 1., 1.])

In [28]:
# MATRIX OF ONES :

# np.ones(row,column)

np.ones((4,5))  #i.e 4 rows , 5 columns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
# MATRIX OF ALL (n) SAME ELEMENTS USING MATRIX OF ONES:
# n*np.ones((row,column))

5*np.ones((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [24]:
# Diagonal Matrix using 'arange' & 'linsapce'

# variable = np.arange(range of elements).reshape(row,column)
x = np.arange(30).reshape(5,6) # values in range or product of row & column must be same , otherwise it will be unbalanced. 
x   # or print(x)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

## RANDOM NUMBER GENERATION : will study rand , randn & randint one by one.

In [23]:
# In 'arange' we actually knows the values which we want to print  , BUT in 'Random number generation' output will be random.

# np.random.seed(n)   #  each seed will print similar data , and 'n' may be anything.

np.random.seed(6)
print('random no. generation(from uniform distribution)')

# print(np.random.rand(row,column))

print(np.random.rand(10,6))

# here random is for all random numbers , but seed will give similar data always

# properties of rand :
# all values will be +ve , less than 1 float values and almost approx to each other(i.e uniform)

random no. generation(from uniform distribution)
[[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785 0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551  0.99022427 0.8198582  0.41320093]
 [0.87626766 0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
 [0.70913175 0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591 0.71733215]
 [0.93734953 0.35180977 0.2536341  0.40247251 0.74651072 0.72407057]
 [0.4061078  0.98937985 0.45049928 0.37380843 0.70962861 0.08245855]
 [0.39837292 0.77088097 0.76475098 0.28385938 0.18954219 0.47125096]
 [0.33480604 0.73473504 0.18910712 0.33110407 0.84422842 0.61502403]]


In [22]:
## RANDN i.e randn(): may be +ve or -ve , float values , it will give bell shape curve(norml distribution) not uniform.

# .seed don't work here in randn, it will always print different data.

print("numbers from normal distribution with zero mean and standard deviation one")
print(np.random.randn(10,6))

numbers from normal distribution with zero mean and standard deviation one
[[-0.19182994 -0.10743127 -2.19924847  1.40525682 -0.06680966 -1.74604402]
 [-0.06627533  0.35258264  1.59363877  1.20166403  3.80940557 -1.33159554]
 [-0.98005032 -0.72330662 -0.06080195 -0.88252548  0.52755774 -0.45542401]
 [-0.09687483 -0.15104131 -1.02383823  0.11460261 -1.46091976 -0.51691196]
 [-0.96460663 -0.81851483  0.32148336  0.62717233  1.51850894  0.50281221]
 [-0.51937652 -0.55562103 -0.37066982  1.41141525 -0.20991876 -0.80523002]
 [-0.12888396  0.27878497  0.46897124  0.42673545  0.86664299 -0.31906599]
 [ 0.23522417 -0.4858554  -1.1738736   0.42786623  0.15425998 -0.03023139]
 [ 0.21825493 -0.46532805  1.59855835 -0.11842991  1.82779599 -1.22127309]
 [ 0.88566411  0.42013036 -0.28224653 -0.8180432  -1.62563621  0.17779913]]


In [21]:
## RANDINT i.e randint(): it will print integer values as other gives float values.

# np.random.randint(start(low) , stop(high) , no. of values(size) )

np.random.randint(10,20,5)

array([14, 18, 11, 17, 11])

In [20]:
## RANDINT IN MATRIX:

#np.random.randint(start(low),stop(high),(row,column))

np.random.randint(1,100,(3,4)) # random integer numbers in between 1 t0 100 of order 3*4

array([[70, 56, 62, 70],
       [48, 77, 39, 47],
       [81,  5, 66, 50]])

## Real time example of randint:

In [19]:
import numpy as np
while True :
    otp1=np.random.randint(1000,10000,1)  # 4 digit random integer number b/w data , size =1
    print('Your Otp is',otp1)
    user_otp =int(input('Enter Otp'))
    if otp1 ==user_otp:
        print('Login Success')
        break
    else:
        print('invalid otp , generate new otp')
    continue
    

Your Otp is [7450]
Enter Otp1250
invalid otp , generate new otp
Your Otp is [7733]
Enter Otp5268
invalid otp , generate new otp
Your Otp is [6437]
Enter Otp4845
invalid otp , generate new otp
Your Otp is [1254]
Enter Otp1254
Login Success


## Reshaping Other ways

In [41]:
import numpy as np
from numpy.random import randint as ri

#variable = ri(start, stop, size)

a=ri(10,20,30) # 3 random integer b/w given data
a

array([12, 19, 16, 12, 15, 12, 17, 15, 11, 11, 17, 15, 14, 12, 18, 18, 17,
       18, 10, 18, 19, 12, 10, 17, 16, 10, 17, 15, 11, 18])

In [42]:
# Reshape in MATRIX : Remember total elemets and product of rows & column must be same: as 30 or (6,5)

c = a.reshape(6,5)
c            # same numbers'a' but in Matrix form

array([[12, 19, 16, 12, 15],
       [12, 17, 15, 11, 11],
       [17, 15, 14, 12, 18],
       [18, 17, 18, 10, 18],
       [19, 12, 10, 17, 16],
       [10, 17, 15, 11, 18]])

In [43]:
# MINIMUM & MAXIMUM VALUES :

print('Minimum value is',c.min())
print('Maximum value is',c.max())

Minimum value is 10
Maximum value is 19


In [45]:
# MEAN :

#np.mean(value/variable)

np.mean(c)

14.733333333333333

## SORTING

In [48]:
M = ri(1,100,25).reshape(5,5) # matrix of random integers
print('\n 5*5 Matrix of random integers is :\n',M)
print('\n sorted matrix along each row  is :\n',np.sort(M)) # default axis = 1 (row)
print('\n sorted matrix along each column is :\n',np.sort(M ,axis =0))   # axis =0 means column


 5*5 Matrix of random integers is :
 [[ 2 66 26 26 38]
 [92 87 85 75 17]
 [69 99 55 96 67]
 [13 50 48 15 95]
 [27 65 92  3  3]]

 sorted matrix along each row  is :
 [[ 2 26 26 38 66]
 [17 75 85 87 92]
 [55 67 69 96 99]
 [13 15 48 50 95]
 [ 3  3 27 65 92]]

 sorted matrix along each column is :
 [[ 2 50 26  3  3]
 [13 65 48 15 17]
 [27 66 55 26 38]
 [69 87 85 75 67]
 [92 99 92 96 95]]


## NUMPY CONDITIONS

In [51]:
emp_sal = np.random.randint(20000,50000,12) # 12 random integer  values/numbers(salary)
emp_sal


array([27359, 49663, 27866, 27192, 34018, 33019, 33076, 38978, 20099,
       41483, 41801, 28254])

In [52]:
## WHERE i.e np.where: if you want to actual salary/values less than or greatr than some value or with any condition:

np.where(emp_sal<30000)

# it will give the index of those values which we want to find.

# similary you can check for any conditions like ( < , > =, ==,!)

(array([ 0,  2,  3,  8, 11], dtype=int64),)

In [54]:
# if we want to fatch that data not index then:

emp_sal[np.where(emp_sal<30000)]    # must use square bracket to fatch the data.

array([27359, 27866, 27192, 20099, 28254])

In [55]:
## SET MINIMUM & MAXIMUM DATA USING min & max , clip :

# np.clip(variable , a_min=n , a_max=m)

np.clip(emp_sal ,a_min =20000 , a_max =40000) # use clip and a_min , a_max that means set one min and max value.

array([27359, 40000, 27866, 27192, 34018, 33019, 33076, 38978, 20099,
       40000, 40000, 28254])

## INDEXING & SLICING

In [57]:
 # varible = np.arange(start , stop , size)
  
 arr =np.arange(10,20)
print('array:',arr)  

array: [10 11 12 13 14 15 16 17 18 19]


In [59]:
# if want to know the element/value using its index then :

print('element with index 7 is :',arr[7])  # optional method we can go with this too 
# as :
arr[7] # if we dont want to use print.

element with index 7 is : 17


17

In [61]:
# if we want to find multiple elements/ values with their index in a single shot then :

print('element with index 2 , 5 ,7 is :',arr[[2,5,7]]) # firstly pass list then one more bracket formindex , so that it gives us list of multiple values.

# also we can use slicing method i.e [start, stop]

arr[2:7] # from index one to other , also can use step size bedefault it's 1.

element with index 2 , 5 ,7 is : [12 15 17]


array([12, 13, 14, 15, 16])

In [63]:
# MATRIX ( INDEXING & SLICING) : HOW TO EXTRACT DATA FROM MATRIX 

my_mat =[[1,2,3],[4,5,6],[7,8,9]]
mat =np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
# data/element we want fatch in a matrix like matrix_name[row_index][column_index]:

mat[1][2]  # element in row index 1 and column index 2

6

In [68]:
# if we wanr to fatch entire row then : matrix_name[row_index]

mat[2]  # row with index 2 is fethed

array([7, 8, 9])

In [69]:
mat[1]  # row with index 1 is fetched.

array([4, 5, 6])

In [70]:
mat[0]   # row with index 0 is fetched.

array([1, 2, 3])

In [76]:
## for column : if we want to fetch entire column then : matrix_name[row,column]

mat[:,2]  # all rows and column with index 3

array([3, 6, 9])

In [77]:
# if we want to have all column after an particular index with all rows then : matrix_name[:,index:]

mat[:,1:]  # here we got all column after an column with index 1

array([[2, 3],
       [5, 6],
       [8, 9]])

In [78]:
# if we want to have all column before an particular index with all rows then : matrix_name[:,:index]

mat[:,:3] # we only have column wth index 0 ,1,2 not 3 so end part is excluded .


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
# if we want to fetch element using both rows and column then : matrix_name[slicing for row , slicing for column]

mat[1:2,1:2]  #for row with index 1 and for column with index 1 , becoz end index are excluded for both.

array([[5]])

In [80]:
# matrix_name[slicing for row , [values of column i.e a,b]]

mat[0:2,[1,2]]  # here we fetched rows with index 0 and 1 as index 2 is excluded , and column 1 and 2 both .

array([[2, 3],
       [5, 6]])

## UPDATE MATRIX

In [82]:
# to update matrix : matrix_name[row,column]= new value

mat[1,2]=35
mat    # new value is updated at row with index 1 and at column with index 2

array([[ 1,  2,  3],
       [ 4,  5, 35],
       [ 7,  8,  9]])

In [83]:
mat[1,0]=100
mat

array([[  1,   2,   3],
       [100,   5,  35],
       [  7,   8,   9]])

## SUBSETTING:

If we have a Big Matrix (i.e of higher order /shape) , and if we want to consider some part /smaller part or some portion with conditions , then we'll go for subsetting. 

In [5]:
import numpy as np
from numpy.random import randint as ri

In [6]:
mat = np.array(ri(10,100,15)).reshape(3,5)
# here 'ri' is randomint which takes random integer values ,reshape gives matrix of rows and columns.
mat

array([[38, 70, 19, 49, 73],
       [22, 38, 85, 81, 96],
       [70, 19, 26, 72, 27]])

In [7]:
# if want so select some portion with condition like >,<,== , then we call it subsetting.
mat>50

# true false means it is checking condition with all elements , if >50 then true otherwise false.

array([[False,  True, False, False,  True],
       [False, False,  True,  True,  True],
       [ True, False, False,  True, False]])

In [8]:
# if want elements after condition checked , like if we want some portion/part then:

mat[mat>50]

array([70, 73, 85, 81, 96, 70, 72])

In [11]:
# we can also use 'np.where' to return some data based on comdition

marks =50
np.where(marks>68 , 'pass','fail')    



array('fail', dtype='<U4')

In [12]:
marks=70
np.where(marks>69 , 'pass','fail')

array('pass', dtype='<U4')

In [21]:
# Check non-zeros:

non_zero = ri(-10,50,100)
print(non_zero)


[ 27  10  25   1   0  48 -10   5   7  -7  25  27   5  27   1  -9 -10  39
  15  31  33  43  45   9   4  -3  -3  33  44  38  21  45  46   3  -2  17
  20   6   5  41   5  41  30  23  -9  33  20  21   0  18   4  -4  -9  41
  45  13  49  12  33  28  22  -7 -10   2  19  46  12  12   0  17   0  -6
  45  35  44  44  27  25  17  11   7   4  35  44  23  33   7  41  34  29
  42  28  49  34   3  31   9  26  37  -4]


In [22]:
# if we want to count non_zero , then :
# np.count_nonzero(filename)

np.count_nonzero(non_zero)

96

In [23]:
# 'Ravel' or 'Flatten' : This concept is used in Deep earning for Image Processing:

array= np.array(ri(0,20,(3,4)))
array

array([[ 9,  9,  5, 11],
       [ 8,  6,  9, 12],
       [ 2,  4,  9,  8]])

In [24]:
# filename.ravel(): 'ravel' means it will give data in one line.

array.ravel()

array([ 9,  9,  5, 11,  8,  6,  9, 12,  2,  4,  9,  8])

In [25]:
# filename.flatten(): 'flatten' also gives data in a line . both are exactly same.

array.flatten()

array([ 9,  9,  5, 11,  8,  6,  9, 12,  2,  4,  9,  8])

## Universal Functions:

In [29]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)

mat1


array([[1, 3, 2],
       [2, 5, 8],
       [9, 1, 2]])

In [30]:
mat2 = np.array(ri(1,10,9)).reshape(3,3)

mat2


array([[8, 4, 7],
       [1, 8, 7],
       [9, 9, 7]])

In [31]:
## Universal function like additin:

mat1+mat2

array([[ 9,  7,  9],
       [ 3, 13, 15],
       [18, 10,  9]])

In [32]:
# like multiplication :

mat1*mat2

array([[ 8, 12, 14],
       [ 2, 40, 56],
       [81,  9, 14]])

In [33]:
# like subtraction :

mat1-mat2

array([[-7, -1, -5],
       [ 1, -3,  1],
       [ 0, -8, -5]])

## BROADCASTING

In [ ]:
# numpy operations are  usually done in pairs of arrays on an element by element basis
# In the simplest case , the two arrays must have exactly the same shape.
# NumPy's Broadcasting rule relaxes this constraint when the arrays shape meets certain constraint
# When operating on two arrays, NumPy comapares thier shape elementwise. It starts with the Trailing.
# Two dimensions are compatible when they are equal and one of them is 1.



In [35]:
start = np.zeros((3,3))
start

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
# Create a rank 1 ndarray with three values i.e of 1*3

arr = np.array([[1,5,6]])
arr

array([[1, 5, 6]])

In [38]:
now = start+arr
now


array([[1., 5., 6.],
       [1., 5., 6.],
       [1., 5., 6.]])

In [47]:
# TRANPOSE (filename.T) ; here .T used for Transpose.

new_row = arr.T
new_row

array([[1],
       [5],
       [6]])

In [49]:
# now add matrix to transposed array:

start+new_row

array([[1., 1., 1.],
       [5., 5., 5.],
       [6., 6., 6.]])

## NUMPY COMPLETED